version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nodeapp
  
  nodeapp:
    build: 
      context: .
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=user1
      - MONGO_PASSWORD=user1
    command: npm run dev 
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: user1
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    